<?php
%A%
<form<?php echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form = $_form = $_control["myForm"], array (
), FALSE) ?>>
	<button<?php $_input = $_form["send"]; echo $_input->getControl()->attributes() ?>>
		description of button
	</button>

	<button<?php $_input = $_form["send"]; echo $_input->getControl()->attributes() ?>></button>

	<button<?php $_input = $_form["send"]; echo $_input->getControl()->attributes() ?>
><?php echo htmlspecialchars($_input->caption) ?></button>
<?php echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd($_form, FALSE) ?></form>
<?php
}}
